
CREATE TABLE IF NOT EXISTS NOBEL_WIN (
  YEAR INTEGER,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);

-- Insert sample data into the NOBEL_WIN table
INSERT INTO NOBEL_WIN  VALUES(1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST');
INSERT INTO NOBEL_WIN  VALUES(1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST');
INSERT INTO NOBEL_WIN  VALUES(1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST');
INSERT INTO NOBEL_WIN  VALUES(1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST');
INSERT INTO NOBEL_WIN  VALUES(1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST');
INSERT INTO NOBEL_WIN  VALUES(1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST');
INSERT INTO NOBEL_WIN  VALUES(1973,'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER');
INSERT INTO NOBEL_WIN  VALUES(1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT');
INSERT INTO NOBEL_WIN  VALUES(1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST');
INSERT INTO NOBEL_WIN  VALUES(1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');

select * from NOBEL_WIN;
select * from NOBEL_WIN where SUBJECT  not like 'P%';
select * from NOBEL_WIN where SUBJECT not like 'B%';
select * from NOBEL_WIN where SUBJECT like 'P%';

select * from NOBEL_WIN order by YEAR;
select * from NOBEL_WIN order by YEAR DESC;


select SUBJECT as "SUBJECT",
count(*) as "number of winners" 
from NOBEL_WIN
group by SUBJECT;
